[04-12-2021 15:48:22.533]: ERROR: null
[Exception: null]
   [Stacktrace:(app.ppob.controller.General:setFooterStruk:823)]
  [Stacktrace:(app.ppob.controller.General:setFooter:817)]
  [Stacktrace:(app.ppob.controller.VoucherController:updateSuccessTranmain:425)]
  [Stacktrace:(app.ppob.controller.VoucherController:perfomPayment:318)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:162)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:153)]
  [Stacktrace:(javafx.concurrent.Task$TaskCallable:call:1423)]
  [Stacktrace:(java.util.concurrent.FutureTask:run:-1)]
  [Stacktrace:(javafx.concurrent.Service:lambda$null$6:725)]
  [Stacktrace:(java.security.AccessController:doPrivileged:-2)]
  [Stacktrace:(javafx.concurrent.Service:lambda$executeTask$7:724)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor:runWorker:-1)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor$Worker:run:-1)]
  [Stacktrace:(java.lang.Thread:run:-1)]

[04-12-2021 16:06:12.131]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:06:17.664]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:11:50.995]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:11:56.062]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:11:58.813]: ERROR: JSONObject["201870"] not found.
[Exception: JSONObject["201870"] not found.]
   [Stacktrace:(org.json.JSONObject:get:573)]
  [Stacktrace:(app.ppob.controller.PLNPostpaidController:updateSuccessTranmain:426)]
  [Stacktrace:(app.ppob.controller.PLNPostpaidController:perfomPayment:152)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:156)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:147)]
  [Stacktrace:(javafx.concurrent.Task$TaskCallable:call:1423)]
  [Stacktrace:(java.util.concurrent.FutureTask:run:-1)]
  [Stacktrace:(javafx.concurrent.Service:lambda$null$6:725)]
  [Stacktrace:(java.security.AccessController:doPrivileged:-2)]
  [Stacktrace:(javafx.concurrent.Service:lambda$executeTask$7:724)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor:runWorker:-1)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor$Worker:run:-1)]
  [Stacktrace:(java.lang.Thread:run:-1)]

[04-12-2021 16:13:46.827]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:13:50.241]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:13:58.906]: ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MMY-VSI-532110000113","info1":"Informasi Hubungi Call Center: 123 Atau Hub. PLN ' at line 1
[Exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MMY-VSI-532110000113","info1":"Informasi Hubungi Call Center: 123 Atau Hub. PLN ' at line 1]
   [Stacktrace:(sun.reflect.NativeConstructorAccessorImpl:newInstance0:-2)]
  [Stacktrace:(sun.reflect.NativeConstructorAccessorImpl:newInstance:-1)]
  [Stacktrace:(sun.reflect.DelegatingConstructorAccessorImpl:newInstance:-1)]
  [Stacktrace:(java.lang.reflect.Constructor:newInstance:-1)]
  [Stacktrace:(com.mysql.jdbc.Util:handleNewInstance:411)]
  [Stacktrace:(com.mysql.jdbc.Util:getInstance:386)]
  [Stacktrace:(com.mysql.jdbc.SQLError:createSQLException:1053)]
  [Stacktrace:(com.mysql.jdbc.MysqlIO:checkErrorPacket:4120)]
  [Stacktrace:(com.mysql.jdbc.MysqlIO:checkErrorPacket:4052)]
  [Stacktrace:(com.mysql.jdbc.MysqlIO:sendCommand:2503)]
  [Stacktrace:(com.mysql.jdbc.MysqlIO:sqlQueryDirect:2664)]
  [Stacktrace:(com.mysql.jdbc.ConnectionImpl:execSQL:2788)]
  [Stacktrace:(com.mysql.jdbc.StatementImpl:executeUpdate:1816)]
  [Stacktrace:(com.mysql.jdbc.StatementImpl:executeUpdate:1730)]
  [Stacktrace:(co.id.eazy.query.service.QueryService:executeQueryUpdate:78)]
  [Stacktrace:(co.id.eazy.query.service.QueryService:sendQueryInsert:84)]
  [Stacktrace:(app.ppob.controller.General:insertToDatabase:233)]
  [Stacktrace:(app.ppob.controller.General:insertToSaleTemp:625)]
  [Stacktrace:(app.ppob.controller.PLNPostpaidController:updateSuccessTranmain:432)]
  [Stacktrace:(app.ppob.controller.PLNPostpaidController:perfomPayment:152)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:156)]
  [Stacktrace:(app.ppob.controller.General$1$1:call:147)]
  [Stacktrace:(javafx.concurrent.Task$TaskCallable:call:1423)]
  [Stacktrace:(java.util.concurrent.FutureTask:run:-1)]
  [Stacktrace:(javafx.concurrent.Service:lambda$null$6:725)]
  [Stacktrace:(java.security.AccessController:doPrivileged:-2)]
  [Stacktrace:(javafx.concurrent.Service:lambda$executeTask$7:724)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor:runWorker:-1)]
  [Stacktrace:(java.util.concurrent.ThreadPoolExecutor$Worker:run:-1)]
  [Stacktrace:(java.lang.Thread:run:-1)]

[04-12-2021 16:15:19.943]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[04-12-2021 16:15:23.926]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[16-12-2021 20:43:24.498]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[16-12-2021 20:43:38.511]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[16-12-2021 20:43:46.169]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[19-12-2021 18:56:56.158]: Error Response from biller. [Exception: timeout ]
  [Stack trace: (org.testcontainers.shaded.okio.Okio$4:newTimeoutException:232)]
  [Stack trace: (org.testcontainers.shaded.okio.AsyncTimeout:exit:285)]
  [Stack trace: (org.testcontainers.shaded.okio.AsyncTimeout$2:read:241)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:indexOf:354)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:readUtf8LineStrict:226)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readHeaderLine:215)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readResponseHeaders:189)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor:intercept:88)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor:intercept:45)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor:intercept:126)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:getResponseWithInterceptorChain:254)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:execute:92)]
  [Stack trace: (app.ppob.controller.handler.AbstractHandler:sendOKHttpGETRequest:145)]
  [Stack trace: (app.ppob.controller.handler.BillerJSONMessageHandler:sendGetRequestToGateway:105)]
  [Stack trace: (app.ppob.controller.deposit.Saldo:lambda$run$0:33)]
  [Stack trace: (com.sun.javafx.application.PlatformImpl:lambda$null$5:295)]
  [Stack trace: (java.security.AccessController:doPrivileged:-2)]
  [Stack trace: (com.sun.javafx.application.PlatformImpl:lambda$runLater$6:294)]
  [Stack trace: (com.sun.glass.ui.InvokeLaterDispatcher$Future:run:95)]
  [Stack trace: (com.sun.glass.ui.win.WinApplication:_runLoop:-2)]
  [Stack trace: (com.sun.glass.ui.win.WinApplication:lambda$null$4:185)]
  [Stack trace: (java.lang.Thread:run:-1)]
[19-12-2021 18:57:17.615]: Error Response from biller. [Exception: Connection reset ]
  [Stack trace: (java.net.SocketInputStream:read:-1)]
  [Stack trace: (java.net.SocketInputStream:read:-1)]
  [Stack trace: (org.testcontainers.shaded.okio.Okio$2:read:140)]
  [Stack trace: (org.testcontainers.shaded.okio.AsyncTimeout$2:read:237)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:indexOf:354)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:readUtf8LineStrict:226)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readHeaderLine:215)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readResponseHeaders:189)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor:intercept:88)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor:intercept:45)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor:intercept:126)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:getResponseWithInterceptorChain:254)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:execute:92)]
  [Stack trace: (app.ppob.controller.handler.AbstractHandler:sendOKHttpGETRequest:145)]
  [Stack trace: (app.ppob.controller.handler.BillerJSONMessageHandler:sendGetRequestToGateway:105)]
  [Stack trace: (app.ppob.controller.deposit.Saldo:lambda$run$0:33)]
  [Stack trace: (com.sun.javafx.application.PlatformImpl:lambda$null$5:295)]
  [Stack trace: (java.security.AccessController:doPrivileged:-2)]
  [Stack trace: (com.sun.javafx.application.PlatformImpl:lambda$runLater$6:294)]
  [Stack trace: (com.sun.glass.ui.InvokeLaterDispatcher$Future:run:95)]
  [Stack trace: (com.sun.glass.ui.win.WinApplication:_runLoop:-2)]
  [Stack trace: (com.sun.glass.ui.win.WinApplication:lambda$null$4:185)]
  [Stack trace: (java.lang.Thread:run:-1)]
[19-12-2021 18:58:52.715]: Error Response from biller. [Exception: Read timed out ]
  [Stack trace: (java.net.SocketInputStream:socketRead0:-2)]
  [Stack trace: (java.net.SocketInputStream:socketRead:-1)]
  [Stack trace: (java.net.SocketInputStream:read:-1)]
  [Stack trace: (java.net.SocketInputStream:read:-1)]
  [Stack trace: (org.testcontainers.shaded.okio.Okio$2:read:140)]
  [Stack trace: (org.testcontainers.shaded.okio.AsyncTimeout$2:read:237)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:indexOf:354)]
  [Stack trace: (org.testcontainers.shaded.okio.RealBufferedSource:readUtf8LineStrict:226)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readHeaderLine:215)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http1.Http1Codec:readResponseHeaders:189)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.CallServerInterceptor:intercept:88)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.connection.ConnectInterceptor:intercept:45)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.cache.CacheInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.BridgeInterceptor:intercept:93)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RetryAndFollowUpInterceptor:intercept:126)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:147)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.internal.http.RealInterceptorChain:proceed:121)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:getResponseWithInterceptorChain:254)]
  [Stack trace: (org.testcontainers.shaded.okhttp3.RealCall:execute:92)]
  [Stack trace: (app.ppob.controller.handler.AbstractHandler:sendOKHttpPOSTRequest:113)]
  [Stack trace: (app.ppob.controller.handler.BillerJSONMessageHandler:sendRequestToGateway:75)]
  [Stack trace: (app.ppob.controller.VoucherController:performInquiry:309)]
  [Stack trace: (app.ppob.controller.General$1$1:call:166)]
  [Stack trace: (app.ppob.controller.General$1$1:call:159)]
  [Stack trace: (javafx.concurrent.Task$TaskCallable:call:1423)]
  [Stack trace: (java.util.concurrent.FutureTask:run:-1)]
  [Stack trace: (javafx.concurrent.Service:lambda$null$6:725)]
  [Stack trace: (java.security.AccessController:doPrivileged:-2)]
  [Stack trace: (javafx.concurrent.Service:lambda$executeTask$7:724)]
  [Stack trace: (java.util.concurrent.ThreadPoolExecutor:runWorker:-1)]
  [Stack trace: (java.util.concurrent.ThreadPoolExecutor$Worker:run:-1)]
  [Stack trace: (java.lang.Thread:run:-1)]
[19-12-2021 19:30:01.325]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[19-12-2021 19:34:10.657]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[19-12-2021 19:35:32.779]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

[19-12-2021 19:35:53.194]: Error Inser Log Message
   java.lang.Thread.run(Unknown Source)

